reporter: spec
dry-run: null
hookfiles: ./tests/dredd-hooks.js
language: nodejs
server-wait: 0
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: true
method: []
color: true
loglevel: warning
path: []
hooks-worker-timeout: 10000
hooks-worker-connect-timeout: 3000
hooks-worker-connect-retry: 1000
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 10000
hooks-worker-term-retry: 1000
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./schemas/api-schema.yaml
endpoint: http://localhost:3000
emitErrors: true
